name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  simple_animations: ^5.0.0  # Versión actualizada (el nombre correcto es simple_animations, no simple_animation)
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/choso2.jpg
    - assets/images/re.jpg
    - assets/images/reo.jpg
    - assets/images/re2.jpg